Lesson1/Models/Catalogue.cs
namespace Lesson1.Models;

public class Catalogue
{
    public List<Category>? Categories { get; set; } = new();
    public List<Product>? Products { get; set; } = new();
}

Lesson1/Models/Category.cs
namespace Lesson1.Models;

public class Category
{
    public int Id { get; set; }
    public string? Name { get; set; }
}

Lesson1/Models/ErrorViewModel.cs
namespace Lesson1.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Lesson1/Models/Product.cs
namespace Lesson1.Models;

public class Product
{
    public int Id { get; set; }
    public string? Name { get; set; } = null;
    public string? Image { get; set; } = null;
}

Lesson1/Controllers/CatalogueController.cs
using Lesson1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lesson1.Controllers;
public class CatalogueController : Controller
{
    private static Catalogue _catalogue = new();

    [HttpGet]
    public IActionResult Categories()
    {
        return View(_catalogue);
    }

    [HttpPost]
    public IActionResult Categories(Category cat)
    {
        _catalogue?.Categories?.Add(cat);
        return View(_catalogue);
    }

    [HttpGet]
    public IActionResult Products()
    {
        if (_catalogue.Products.Count == 0)
        {
            _catalogue.Products.Add(new Product() { Id = 1, Name = "Apple", Image = "https://www.eckes-granini.com/fileadmin/eckesgranini/eckes-granini.com/05-best-of-fruit/fruechte/titelbilder/fruechte-titelbilder-apfel.jpg" });
            _catalogue.Products.Add(new Product() { Id = 2, Name = "Orange", Image = "https://media.istockphoto.com/photos/orange-picture-id185284489?k=20&m=185284489&s=612x612&w=0&h=LLY2os0YTG2uAzpBKpQZOAC4DGiXBt1jJrltErTJTKI=" });
        }
        return View(_catalogue);
    }

    [HttpPost]
    public IActionResult Products(Product prod)
    {
        _catalogue?.Products?.Add(prod);
        return View(_catalogue);
    }
}

Lesson1/Controllers/HomeController.cs
using Lesson1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lesson1.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Lesson1/Views/Catalogue/Categories.cshtml
@model Catalogue?

@{
    ViewData["Title"] = "Categories List";
}

@foreach (var cat in Model.Categories)
{
    <div>@cat.Id @cat.Name</div>
}

<form method="post">
    Id: <input type="text" name="Id" required/>
    <br />
    Name: <input type="text" name="Name"/>
    <br />
    <input type="submit" name="submit" value="Create"/>
</form>

Lesson1/Views/Catalogue/Products.cshtml
@model Catalogue?

@{
    ViewData["Title"] = "Products List";
}

@foreach (var cat in Model.Products)
{
    <div>
        ------
        <img src="@cat.Image" width="100" height="100">
        @cat.Id
        -
        @cat.Name
    </div>
}

<form method="post">
    Id: <input type="text" name="Id" required/>
    <br />
    Name: <input type="text" name="Name"/>
    <br />
    Image Link: <input type="text" name="Image"/>
    <br />
    <input type="submit" name="submit" value="Create"/>
</form>

Lesson1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lesson1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lesson1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lesson1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lesson1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalogue" asp-action="Categories">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalogue" asp-action="Products">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Lesson1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>